name: OpenVINO backend (Windows)

on: [push, pull_request]

jobs:

  job:
    runs-on: windows-2019
    env:
      OPENVINO_VERSION: 2021.4.582

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download OpenVINO Toolkit
      shell: pwsh
      run: |
        Import-Module BitsTransfer
        Start-BitsTransfer -Source https://registrationcenter-download.intel.com/akdlm/irc_nas/17987/w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe -Destination w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe

    - name: Install OpenVINO Toolkit
      shell: cmd
      run: |
        .\w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe --s --f temp --r yes --a install --eula=accept --output=install_status.txt
        "C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat"

    - uses: actions/checkout@v2
      with:
        ref: main
        path: baseline
        fetch-depth: 0

    - name: Update DEPS for main branch
      shell: pwsh
      run: |
        cd baseline
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_onnxruntime': True", "'checkout_onnxruntime': False" | Set-Content -path .\DEPS
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_samples': True", "'checkout_samples': False" | Set-Content -path .\DEPS

    - name: Sync code for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd baseline
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd baseline
        gn gen out\Release --args="webnn_enable_openvino=true is_debug=false"

    - name: Build for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd baseline
        ninja -C out\Release

    - name: Test for main branch
      shell: cmd
      run: |
        baseline\workflow_scripts\test_by_openvino_windows.bat baseline || true
        rmdir /s /q baseline

    - uses: actions/checkout@v2
      with:
        path: update
        fetch-depth: 0

    - name: Update DEPS for update branch
      shell: pwsh
      run: |
        cd update
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_onnxruntime': True", "'checkout_onnxruntime': False" | Set-Content -path .\DEPS
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_samples': True", "'checkout_samples': False" | Set-Content -path .\DEPS

    - name: Sync latest code
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        gn gen out\Release --args="webnn_enable_openvino=true is_debug=false"

    - name: Build for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        ninja -C out\Release

    - name: Test for update branch
      shell: cmd
      run: |
        update\workflow_scripts\test_by_openvino_windows.bat update || true

    - name: Regression check
      run: |
        echo "Regression checking..."
        python update\workflow_scripts\regression_check.py ${{ github.workspace }}\..\baseline_end2endtests.json ${{ github.workspace }}\..\update_end2endtests.json
