name: Check memory leak for OpenVINO backend (Windows)

on: [push, pull_request]

jobs:

  job:
    runs-on: windows-2019
    env:
      OPENVINO_VERSION: 2021.4.582

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download OpenVINO Toolkit
      shell: pwsh
      run: |
        Import-Module BitsTransfer
        Start-BitsTransfer -Source https://registrationcenter-download.intel.com/akdlm/irc_nas/17987/w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe -Destination w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe

    - name: Install OpenVINO Toolkit
      shell: cmd
      run: |
        .\w_openvino_toolkit_p_${{ env.OPENVINO_VERSION }}.exe --s --f temp --r yes --a install --eula=accept --output=install_status.txt
        "C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat"

    - uses: actions/checkout@v2
      with:
        path: update
        fetch-depth: 0

    - name: Sync latest code
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        gn gen out\Debug --args="webnn_enable_openvino=true is_debug=true"

    - name: Build for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        ninja -C out\Debug

    - name: Check memory leak for update branch
      shell: cmd
      run: |
        echo Setup OpenVINO environment...
        call "C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat"
        echo Run WebNN End2End tests by OpenVINO backend on Windows platform...
        call cd update
        out\Debug\webnn_end2end_tests.exe --gtest_filter=-GemmTests.ScalarBias:Pool2dTests.MaxPool2dDilationsDefault:Pool2dTests.MaxPool2dDilationsNhwc:Pool2dTests.*Pool2dAutoPadExplicitOutputSizes4x4Nhwc:Pool2dTests.*Pool2dAutoPadExplicitRoundingTypeCeilNhwc > update_end2endtests.txt || true
        findstr /s /n "Detected memory leaks!" update_end2endtests.txt && python -c "raise Exception('Detected memory leaks!')"
