name: Check memory leak for DirectML backend (Windows)

on: [push, pull_request]

jobs:

  job:

    runs-on: windows-latest

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v2
      with:
        ref: main
        path: baseline
        fetch-depth: 0

    - name: Sync code for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd baseline
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"

        cd baseline
        gn gen out\Debug --args="webnn_enable_dml=true is_debug=true"

    - name: Build for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd baseline
        ninja -C out\Debug

    - name: Check memory leak for main branch
      shell: cmd
      run: |
        cd baseline
        echo "Run End2End Tests..."
        out\Debug\webnn_end2end_tests.exe --gtest_output=json:${{ github.workspace }}\..\baseline_end2endtests.json > baseline_end2endtests.txt
        findstr /s /n "Detected memory leaks!" baseline_end2endtests.txt > baseline_check_result.txt
        findstr "." baseline_check_result.txt || echo "No memory leaks error detected"
        cd ..
        rmdir /s /q baseline

    - uses: actions/checkout@v2
      with:
        path: update
        fetch-depth: 0

    - name: Sync latest code
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        gn gen out\Debug --args="webnn_enable_dml=true is_debug=true"

    - name: Build for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        ninja -C out\Debug

    - name: Check memory leak for update branch
      shell: cmd
      run: |
        cd update
        echo "Run End2End Tests..."
        out\Debug\webnn_end2end_tests.exe --gtest_output=json:${{ github.workspace }}\..\update_end2endtests.json > update_end2endtests.txt || true
        findstr /s /n "Detected memory leaks!" update_end2endtests.txt > update_check_result.txt
        findstr "." update_check_result.txt || echo "No memory leaks error detected"

